### PR TITLE
bump to rc3

### PR DESCRIPTION
**Pull request by PatrickLang**
I'm calling this script as part of my Azure DevTest Lab formula. Works great :)

### CODE REVIEW

**Comment by StefanScherer** [comment]
Thank you Patrick!

**Comment by StefanScherer** [comment]
@PatrickLang I have seen Azure DevTest Lab the first time at TechSummit 2016 this week and haven't used it yet. How easy is it to share such formulas eg. on GitHub?

**Comment by PatrickLang** [comment]
yes :) https://github.com/PatrickLang/artifacts

**Comment by StefanScherer** [comment]
Oh, that's neat. I'll have a close look at it tomorrow :-)

**Pull request merged**
